services:
  postgres:
    image: postgres:16
    restart: unless-stopped
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=loms_db
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - app-network
    command: [ "postgres" ]
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U root -d loms_db" ]
      interval: 5s
      retries: 5

  loms-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: loms-service
    expose:
      - "50051"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=loms_db
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "50051:50051"

  cart-service:
#    build:
#      context: ../cart
#      dockerfile: Dockerfile
    image: vestamart/cart
    container_name: cart-service
    expose:
      - "8082"
    networks:
      - app-network
    ports:
      - "8082:8082"

networks:
  app-network:
    driver: bridge

