// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package postgres

import (
	"context"
)

type Querier interface {
	GetBySKIStocks(ctx context.Context, sku int32) (*GetBySKIStocksRow, error)
	GetInfoFromOrders(ctx context.Context, orderID int64) (*GetInfoFromOrdersRow, error)
	InsertItems(ctx context.Context, arg *InsertItemsParams) (int64, error)
	InsertOrder(ctx context.Context, arg *InsertOrderParams) (int64, error)
	InsertOrderItems(ctx context.Context, arg *InsertOrderItemsParams) error
	ReserveCancelStocks(ctx context.Context, arg *ReserveCancelStocksParams) error
	ReserveRemoveStocks(ctx context.Context, arg *ReserveRemoveStocksParams) error
	ReserveStocks(ctx context.Context, arg *ReserveStocksParams) error
	UpdateStatusOrders(ctx context.Context, arg *UpdateStatusOrdersParams) error
}

var _ Querier = (*Queries)(nil)
